name: admin_smart_events
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.11
  flutter_spinkit: ^5.0.0
  expandable: ^5.0.1
  firebase_auth: ^3.3.13
  provider: ^6.0.2
  firebase_core: ^1.0.0
  intl: ^0.17.0
  cloud_firestore: ^3.1.11
  firebase_messaging: any
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  new_version: ^0.3.0
  flutter_local_notifications: any
  csv: ^5.0.1
  sortedmap: ^0.5.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.5
  image_cropper: ^1.2.1
  pdf_render: ^1.0.13
  flutter_localizations:
    sdk: flutter
  permission_handler: ^9.2.0
  flutter_pdfview: ^1.2.1
  rxdart: ^0.27.3
  hand_signature: ^2.1.0+2
  package_info_plus: ^1.3.0
  flutter_beep: ^1.0.0
  fl_chart: ^0.50.1
  syncfusion_flutter_gauges: ^20.1.47
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^2.0.0
  animated_dialog_box: ^0.0.2
  cloud_functions: ^3.2.5
  validators: ^3.0.0
  modal_bottom_sheet: ^2.0.0
  flex_color_picker: ^2.1.2
  overlay_support: ^1.2.1
  file_picker: ^4.3.2
  qr_flutter: ^4.0.0
  syncfusion_flutter_pdf: ^20.1.47-beta.1
  dependency_validator: ^3.2.0
  in_app_update: ^3.0.0
  random_color: ^1.0.6-nullsafety
  card_swiper: ^2.0.3
  qr_code_scanner: ^0.7.0
  excel: ^2.0.0-null-safety-3
  share: ^2.0.4
  rounded_loading_button: ^2.1.0
  shimmer: ^2.0.0
  shared_preferences: ^2.0.13
  circular_reveal_animation: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  country_currency_pickers: ^2.0.0
  another_flushbar: 1.10.27
  libphonenumber_plugin: ^0.2.3
  photo_view: ^0.14.0
  linkwell: ^2.0.6





flutter_icons:
  image_path: "assets/icon_transparent.png"
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Aphrodite
      fonts:
        - asset: assets/Aphrodite/aphrodite.ttf
          weight: 400
    - family: Rebecca
      fonts:
        - asset: assets/Rebecca/rebecca_samuels.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico/Pacifico-Regular.ttf
          weight: 400
    - family: Goudy
      fonts:
        - asset: assets/Sorts_Mill_Goudy/SortsMillGoudy-Regular.ttf
          weight: 400
  uses-material-design: true

